---
title: "EDA"
author: "Tong Sun"
date: "4/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data1 <- read.csv("Admission.csv")
data2 <- read.csv("Claim.csv")
library(dplyr)
total <- dplyr::left_join(data1, data2, by = "PATIENT_ID")
total_exp1 <- total[ , c(1,4,12,37)]
duplicated(total_exp1)
totAL_exp2 <- total_exp1[!duplicated(total_exp1), ]
df <- totAL_exp2[order(totAL_exp2$DISCHARGE_DATE),]

## Allowed_amount_by_state
library(ggplot2)
ggplot(data = df, aes(x = DISCHARGE_DATE, y = ALLOWED_AMOUNT)) + geom_line(aes(color = STATE_CODE))
## Allowed_amount_distribution
ggplot(df, aes(x = ALLOWED_AMOUNT)) +
  geom_histogram(aes(y = ..density..), binwidth = .5, color = "black", fill = "white") +
  geom_density(alpha = .2, fill = "#FF6666")
## Allowed_amount_by_provider_type
total_exp3 <- total[, c(1,4,37,40)]
duplicated(total_exp3)
total_exp4 <- total_exp3[!duplicated(total_exp3), ]
df1 <- total_exp4[order(total_exp4$DISCHARGE_DATE),]
ggplot(data = df1, aes(x = DISCHARGE_DATE, y = ALLOWED_AMOUNT)) + geom_line(aes(color = PROVIDER_TYPE))
## Allowed_amount_by_disease
total_exp5 <- total[, c(1,4,8,16,37)]
duplicated(total_exp5)
total_exp6 <- total_exp5[!duplicated(total_exp5), ]
df2 <- total_exp6[order(total_exp6$DISCHARGE_DATE),]
hist(total_exp6$AGE)
# Mutate age_group from the variable age: 30-50,50-70,70-90,>90
df2["age_group"] <- cut(df2$AGE, c(30, 50, 70, 90, Inf), c("30-50", "50-70", "70-90", ">90"), include.lowest = TRUE)
head(df2)
ggplot(data = df2, aes(x = DISCHARGE_DATE, y = ALLOWED_AMOUNT)) + geom_line(aes(color = age_group))
```
